<a href="https://colab.research.google.com/github/ZeyTrack/Titanic---Machine-Learning-from-Disaster/blob/main/lfd_task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Imports and reading the data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder, MinMaxScaler

In [ ]:
original_data = pd.read_csv('/content/drive/MyDrive/LFD/Lab1/Titanic_Data/نسخة من train.csv')
data = original_data.copy()
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
test = pd.read_csv('/content/drive/MyDrive/LFD/Lab1/Titanic_Data/نسخة من test.csv')
test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

## 2.   Feature Engineering

In [ ]:
def get_age_category(row):
  if row.Age <=12:
    return 'Children'
  elif row.Age <= 18:
    return 'Teenagers'
  elif row.Age <= 50:
    return 'Adults'
  else:
    return 'Older'

data['AgeCategory'] = data.apply(get_age_category, axis=1)
test['AgeCategory'] = test.apply(get_age_category, axis=1)

data["FamilySize"] = original_data.SibSp + original_data.Parch
test["FamilySize"] = test.SibSp + test.Parch

data.drop(['SibSp', 'Parch'], axis=1, inplace = True)
test.drop(['SibSp', 'Parch'], axis=1, inplace = True)

data['IsAlone'] = ['yes' if family_size == 0 else 'no' for family_size in data.FamilySize] #read on the comprehension list
test['IsAlone'] = ['yes' if family_size == 0 else 'no' for family_size in test.FamilySize]

data

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin,Embarked,AgeCategory,FamilySize,IsAlone
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN,S,Adults,1,no
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85,C,Adults,1,no
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN,S,Adults,0,yes
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123,S,Adults,1,no
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN,S,Adults,0,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN,S,Adults,0,yes
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42,S,Adults,0,yes
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN,S,Older,3,no
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148,C,Adults,0,yes
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN,Q,Adults,0,yes

##3.  Data Cleaning

In [ ]:
for col_name in test.columns:
  print(col_name)
  print(test[col_name].isna().sum())

PassengerId
0
Pclass
0
Name
0
Sex
0
Age
86
Ticket
0
Fare
1
Cabin
327
Embarked
0
AgeCategory
0
FamilySize
0
IsAlone
0

In [ ]:
# you can drop before from the data before spliting it
data = data.drop(['PassengerId','Ticket','Cabin','Name'],axis = 1)
test = test.drop(['Ticket','Cabin','Name'],axis = 1)

data = data[data.Fare < 100]

# Split data into train and validation sets with shuffling
X_train, X_val, y_train, y_val = train_test_split(data.drop('Survived',axis=1), data['Survived'], test_size=0.15, shuffle=True, random_state=1) #random state for reproducing the same result every run

train = pd.concat([X_train,y_train],axis=1)
val = pd.concat([X_val,y_val],axis=1)

age_means = train.groupby('Survived')['Age'].mean()
X_train['Age'] =  train.apply(lambda row: age_means[row['Survived']] if pd.isnull(row['Age']) else row['Age'], axis=1)
X_val['Age'] =  val.apply(lambda row: age_means[row['Survived']] if pd.isnull(row['Age']) else row['Age'], axis=1)
test['Age'].fillna(X_train.Age.mean(), inplace = True)

test['Fare'].fillna(X_train.Fare.mean(), inplace = True)

X_train['Embarked'].fillna(X_train['Embarked'].mode()[0], inplace = True)
X_val['Embarked'].fillna(X_train['Embarked'].mode()[0], inplace = True)

## 4.   Data Preprocessing

In [ ]:
X_train = pd.get_dummies(X_train, columns = ['Sex','Embarked','IsAlone']) # one hot encoding
X_val = pd.get_dummies(X_val, columns = ['Sex','Embarked','IsAlone']) # one hot encoding
test = pd.get_dummies(test, columns = ['Sex','Embarked','IsAlone']) # one hot encoding

ordinal_encoder = OrdinalEncoder(categories = [['Children', 'Teenagers', 'Adults', 'Older']]) #adding categories order for the mapping
X_train['AgeCategory'] = ordinal_encoder.fit_transform(X_train[['AgeCategory']])
X_val['AgeCategory'] = ordinal_encoder.transform(X_val[['AgeCategory']])
test['AgeCategory'] = ordinal_encoder.transform(test[['AgeCategory']])

normalizer = MinMaxScaler()
for col_name in ['Age', 'Fare']:
  X_train[col_name] = normalizer.fit_transform(X_train[[col_name]])
  X_val[col_name] = normalizer.transform(X_val[[col_name]])
  test[col_name] = normalizer.transform(test[[col_name]])

In [ ]:
X_train

,Pclass,Age,Fare,AgeCategory,FamilySize,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,IsAlone_no,IsAlone_yes
58,2,0.064891,0.296791,0.0,3,1,0,0,0,1,1,0
295,1,0.423600,0.296479,3.0,0,0,1,1,0,0,0,1
615,2,0.334089,0.695187,2.0,3,1,0,0,0,1,1,0
478,3,0.305752,0.080436,2.0,0,0,1,0,0,1,0,1
793,1,0.423600,0.328297,3.0,0,0,1,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
765,1,0.716634,0.833779,3.0,1,1,0,0,0,1,1,0
819,3,0.135733,0.298396,0.0,5,0,1,0,0,1,1,0
74,3,0.447436,0.604233,2.0,0,0,1,0,0,1,0,1
241,3,0.385011,0.165775,3.0,1,1,0,0,1,0,1,0
39,3,0.192406,0.120232,1.0,1,1,0,1,0,0,1,0

using of xgboost model

In [ ]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.10/dist-packages (2.0.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.23.5)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.11.4)

In [ ]:
import xgboost as xgb
from sklearn.metrics import accuracy_score

In [ ]:
# Define the features and target variable
features = X_train.columns
target = 'Survived'

# Create DMatrix objects for XGBoost
dtrain = xgb.DMatrix(X_train[features], label=y_train)
dval = xgb.DMatrix(X_val[features], label=y_val)
dtest = xgb.DMatrix(test[features])

In [ ]:
# Define XGBoost parameters
params = {
    'objective': 'binary:logistic',
    'eval_metric': 'logloss',
    'max_depth': 3,
    'learning_rate': 0.1,
    'subsample': 0.8,
    'colsample_bytree': 0.8,
    'seed': 42
}

# Train the XGBoost model
num_round = 100
model = xgb.train(params, dtrain, num_round, evals=[(dval, 'validation')], early_stopping_rounds=10)

[0]	validation-logloss:0.61403
[1]	validation-logloss:0.58598
[2]	validation-logloss:0.56049
[3]	validation-logloss:0.53972
[4]	validation-logloss:0.51911
[5]	validation-logloss:0.50546
[6]	validation-logloss:0.48536
[7]	validation-logloss:0.46878
[8]	validation-logloss:0.45902
[9]	validation-logloss:0.45143
[10]	validation-logloss:0.44361
[11]	validation-logloss:0.43499
[12]	validation-logloss:0.42670
[13]	validation-logloss:0.42009
[14]	validation-logloss:0.41001
[15]	validation-logloss:0.40377
[16]	validation-logloss:0.39621
[17]	validation-logloss:0.39095
[18]	validation-logloss:0.38728
[19]	validation-logloss:0.38013
[20]	validation-logloss:0.37376
[21]	validation-logloss:0.37075
[22]	validation-logloss:0.36712
[23]	validation-logloss:0.36485
[24]	validation-logloss:0.36249
[25]	validation-logloss:0.35964
[26]	validation-logloss:0.35556
[27]	validation-logloss:0.35394
[28]	validation-logloss:0.35359
[29]	validation-logloss:0.35196
[30]	validation-logloss:0.35002
[31]	validation-logloss:0.34843
[32]	validation-logloss:0.34479
[33]	validation-logloss:0.34490
[34]	validation-logloss:0.34143
[35]	validation-logloss:0.34031
[36]	validation-logloss:0.33917
[37]	validation-logloss:0.33908
[38]	validation-logloss:0.33839
[39]	validation-logloss:0.33997
[40]	validation-logloss:0.33738
[41]	validation-logloss:0.33441
[42]	validation-logloss:0.33481
[43]	validation-logloss:0.33522
[44]	validation-logloss:0.33438
[45]	validation-logloss:0.33270
[46]	validation-logloss:0.33258
[47]	validation-logloss:0.33300
[48]	validation-logloss:0.33049
[49]	validation-logloss:0.32957
[50]	validation-logloss:0.32794
[51]	validation-logloss:0.32699
[52]	validation-logloss:0.32539
[53]	validation-logloss:0.32284
[54]	validation-logloss:0.32198
[55]	validation-logloss:0.32180
[56]	validation-logloss:0.32233
[57]	validation-logloss:0.32236
[58]	validation-logloss:0.32201
[59]	validation-logloss:0.32129
[60]	validation-logloss:0.31906
[61]	validation-logloss:0.31847
[62]	validation-logloss:0.31750
[63]	validation-logloss:0.31681
[64]	validation-logloss:0.31646
[65]	validation-logloss:0.31683
[66]	validation-logloss:0.31731
[67]	validation-logloss:0.31795
[68]	validation-logloss:0.31837
[69]	validation-logloss:0.31910
[70]	validation-logloss:0.31777
[71]	validation-logloss:0.31601
[72]	validation-logloss:0.31532
[73]	validation-logloss:0.31471
[74]	validation-logloss:0.31291
[75]	validation-logloss:0.31361
[76]	validation-logloss:0.31372
[77]	validation-logloss:0.31288
[78]	validation-logloss:0.31182
[79]	validation-logloss:0.31238
[80]	validation-logloss:0.31204
[81]	validation-logloss:0.31239
[82]	validation-logloss:0.31200
[83]	validation-logloss:0.30995
[84]	validation-logloss:0.30896
[85]	validation-logloss:0.30760
[86]	validation-logloss:0.30784
[87]	validation-logloss:0.30638
[88]	validation-logloss:0.30680
[89]	validation-logloss:0.30663
[90]	validation-logloss:0.30586
[91]	validation-logloss:0.30513
[92]	validation-logloss:0.30601
[93]	validation-logloss:0.30580
[94]	validation-logloss:0.30474
[95]	validation-logloss:0.30409
[96]	validation-logloss:0.30377
[97]	validation-logloss:0.30249
[98]	validation-logloss:0.30300
[99]	validation-logloss:0.30303

In [ ]:
# Predict on the test set
y_pred = model.predict(dtest)
# Convert probabilities to binary predictions
predictions = [1 if p >= 0.5 else 0 for p in y_pred]

In [ ]:
# Optionally, evaluate the model on the validation set
y_val_pred = model.predict(dval)
val_predictions = [1 if p >= 0.5 else 0 for p in y_val_pred]
accuracy = accuracy_score(y_val, val_predictions)
print(f'Validation Accuracy: {accuracy}')

Validation Accuracy: 0.8650793650793651

## 3. *Make Predictions and Submit to Kaggle*

In [ ]:
# Create a submission DataFrame
submission = pd.DataFrame({'PassengerId': test['PassengerId'], 'Survived': predictions})

# Save the submission to a CSV file
submission.to_csv('submission.csv', index=False)

## 1. * rank features using a feature importance algorithm*

In [ ]:
from sklearn.ensemble import RandomForestClassifier

# Create a Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=1)

# Train the model
rf_model.fit(X_train, y_train)

# Get feature importances
feature_importances = rf_model.feature_importances_

# Create a DataFrame with feature names and their importance scores
feature_importance_df = pd.DataFrame({'Feature': X_train.columns, 'Importance': feature_importances})

# Sort the DataFrame by importance in descending order
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

# Print the ranked list of features
print(feature_importance_df)
data

        Feature  Importance
1           Age    0.268581
2          Fare    0.217875
6      Sex_male    0.139809
5    Sex_female    0.126625
0        Pclass    0.074885
4    FamilySize    0.061156
3   AgeCategory    0.059544
9    Embarked_S    0.014584
7    Embarked_C    0.012125
10   IsAlone_no    0.008773
11  IsAlone_yes    0.008076
8    Embarked_Q    0.007968

,Survived,Pclass,Sex,Age,Fare,Embarked,AgeCategory,FamilySize,IsAlone
0,0,3,male,22.0,7.2500,S,Adults,1,no
1,1,1,female,38.0,71.2833,C,Adults,1,no
2,1,3,female,26.0,7.9250,S,Adults,0,yes
3,1,1,female,35.0,53.1000,S,Adults,1,no
4,0,3,male,35.0,8.0500,S,Adults,0,yes
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,13.0000,S,Adults,0,yes
887,1,1,female,19.0,30.0000,S,Adults,0,yes
888,0,3,female,NaN,23.4500,S,Older,3,no
889,1,1,male,26.0,30.0000,C,Adults,0,yes
890,0,3,male,32.0,7.7500,Q,Adults,0,yes

## 2. *remove the least important feature based on the feature importance scores*

In [ ]:
# Assuming 'X_train', 'X_val', and 'test' are your DataFrames
# Assuming 'feature_importance_df' is the DataFrame containing feature importances

# Get the least important feature
least_important_feature = feature_importance_df.iloc[-1]['Feature']

# Drop the least important feature from the datasets
X_train = X_train.drop(least_important_feature, axis=1)
X_val = X_val.drop(least_important_feature, axis=1)
test = test.drop(least_important_feature, axis=1)

## 5. Training

1-Prepare the Data:

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from xgboost import XGBClassifier



X_train = data
y_train = data['Survived']

X_test = test

# Identify categorical columns
categorical_cols = [cname for cname in X_train.columns if
                    X_train[cname].nunique() < 10 and
                    X_train[cname].dtype == "object"]

# Identify numerical columns
numerical_cols = [cname for cname in X_train.columns if
                  X_train[cname].dtype in ['int64', 'float64']]

# Preprocessing for numerical data
numerical_transformer = StandardScaler()

# Preprocessing for categorical data
categorical_transformer = OneHotEncoder()

# Bundle preprocessing for numerical and categorical data
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ])

# Define the model
model = XGBClassifier()  # Replace YourModel with the actual model you are using

# Bundle preprocessing and modeling code in a pipeline
#clf = Pipeline(steps=[('preprocessor', preprocessor),
 #                     ('model', model)])
# Create and apply the pipeline
pipeline = Pipeline(steps=[('preprocessor', preprocessor)])
X_train_scaled = pipeline.fit_transform(X_train)

# Split the training data into training and validation sets
#X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Preprocessing of training data, fit model
#clf.fit(X_train, y_train)

# Preprocessing of validation data, get predictions
#y_val_pred = clf.predict(X_val)

## 4. *-Hyperparameter Tuning with RandomizedSearchCV:*

In [ ]:
from datetime import datetime
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from xgboost import XGBClassifier

def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\nTime taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))

params = {
    'min_child_weight': [1, 5, 10],
    'gamma': [0.5, 1, 1.5, 2, 5],
    'subsample': [0.6, 0.8, 1.0],
    'colsample_bytree': [0.6, 0.8, 1.0],
    'max_depth': [3, 4, 5]
}

xgb = XGBClassifier(learning_rate=0.02, n_estimators=600, objective='binary:logistic', silent=True, nthread=1)

folds = 3
param_comb = 5

skf = StratifiedKFold(n_splits=folds, shuffle=True, random_state=1001)

random_search = RandomizedSearchCV(xgb, param_distributions=params, n_iter=param_comb,
                                   scoring='roc_auc', n_jobs=4, cv=skf.split(X_train_scaled, y_train),
                                   verbose=3, random_state=1001)

start_time = timer(None)
random_search.fit(X_train_scaled, y_train)
timer(start_time)

print('\nAll results:')
print(random_search.cv_results_)
print('\nBest estimator:')
print(random_search.best_estimator_)
print('\nBest normalized gini score for %d-fold search with %d parameter combinations:' % (folds, param_comb))
print(random_search.best_score_ * 2 - 1)
print('\nBest hyperparameters:')
print(random_search.best_params_)

Fitting 3 folds for each of 5 candidates, totalling 15 fits

Time taken: 0 hours 0 minutes and 7.01 seconds.

All results:
{'mean_fit_time': array([0.56992054, 0.53443782, 0.36979842, 0.40677253, 0.30703131]), 'std_fit_time': array([0.06629162, 0.0560944 , 0.11714432, 0.03056332, 0.06685035]), 'mean_score_time': array([0.02341827, 0.02131494, 0.02020558, 0.01850565, 0.0117592 ]), 'std_score_time': array([0.00572312, 0.00230388, 0.01103328, 0.00734637, 0.00601013]), 'param_subsample': masked_array(data=[1.0, 0.6, 0.8, 1.0, 0.8],
             mask=[False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_min_child_weight': masked_array(data=[5, 1, 5, 5, 1],
             mask=[False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_max_depth': masked_array(data=[3, 5, 5, 5, 4],
             mask=[False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_gamma': masked_array(data=[5, 1.5, 1, 5, 1],
             mask=[False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_colsample_bytree': masked_array(data=[1.0, 0.8, 0.8, 0.6, 1.0],
             mask=[False, False, False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'subsample': 1.0, 'min_child_weight': 5, 'max_depth': 3, 'gamma': 5, 'colsample_bytree': 1.0}, {'subsample': 0.6, 'min_child_weight': 1, 'max_depth': 5, 'gamma': 1.5, 'colsample_bytree': 0.8}, {'subsample': 0.8, 'min_child_weight': 5, 'max_depth': 5, 'gamma': 1, 'colsample_bytree': 0.8}, {'subsample': 1.0, 'min_child_weight': 5, 'max_depth': 5, 'gamma': 5, 'colsample_bytree': 0.6}, {'subsample': 0.8, 'min_child_weight': 1, 'max_depth': 4, 'gamma': 1, 'colsample_bytree': 1.0}], 'split0_test_score': array([1., 1., 1., 1., 1.]), 'split1_test_score': array([1., 1., 1., 1., 1.]), 'split2_test_score': array([1., 1., 1., 1., 1.]), 'mean_test_score': array([1., 1., 1., 1., 1.]), 'std_test_score': array([0., 0., 0., 0., 0.]), 'rank_test_score': array([1, 1, 1, 1, 1], dtype=int32)}

Best estimator:
XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=1.0, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=5, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.02, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=3, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=600, n_jobs=None, nthread=1,
              num_parallel_tree=None, ...)

Best normalized gini score for 3-fold search with 5 parameter combinations:
1.0

Best hyperparameters:
{'subsample': 1.0, 'min_child_weight': 5, 'max_depth': 3, 'gamma': 5, 'colsample_bytree': 1.0}

/usr/local/lib/python3.10/dist-packages/xgboost/core.py:160: UserWarning: [23:04:28] WARNING: /workspace/src/learner.cc:742:
Parameters: { "silent" } are not used.

  warnings.warn(smsg, UserWarning)